// Auto-generated by scripts/upload-cloudinary-hero.cjs
// These URLs intentionally use the original Cloudinary asset URLs with no transformation parameters.

export const HERO_CLOUDINARY_FOLDER = "Portfolio Minh Huy/Hero Originals";

export const HERO_CLOUDINARY_ASSETS = {
  portraitIllustrationFlowers: {
    secureUrl: "https://res.cloudinary.com/dlasbipjr/image/upload/v1780646027/Portfolio%20Minh%20Huy/Hero%20Originals/portrait-illustration-flowers.jpg",
    publicId: "Portfolio Minh Huy/Hero Originals/portrait-illustration-flowers",
    bytes: 1056402,
    width: 1792,
    height: 2400,
    format: "jpg",
  },
  originalPhoto: {
    secureUrl: "https://res.cloudinary.com/dlasbipjr/image/upload/v1780646028/Portfolio%20Minh%20Huy/Hero%20Originals/original-photo.jpg",
    publicId: "Portfolio Minh Huy/Hero Originals/original-photo",
    bytes: 3104715,
    width: 5016,
    height: 3344,
    format: "jpg",
  },
} as const;

export const PORTRAIT_ILLUSTRATION_FLOWERS_URL = HERO_CLOUDINARY_ASSETS.portraitIllustrationFlowers.secureUrl;
export const ORIGINAL_PHOTO_URL = HERO_CLOUDINARY_ASSETS.originalPhoto.secureUrl;
