// Auto-generated by scripts/upload-project-assets.cjs
// Assets are grouped by portfolio project in Cloudinary.

export const PROJECT_ASSET_ROOT = "Portfolio Minh Huy";

export const PROJECT_ASSETS = {
  "angAng": {
    "brandIdentityLogo": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803348/Portfolio%20Minh%20Huy/Ang%20Ang/Brand/brand-identity-logo.svg",
      "publicId": "Portfolio Minh Huy/Ang Ang/Brand/brand-identity-logo",
      "bytes": 13133,
      "width": 1527,
      "height": 368,
      "format": "svg"
    },
    "verifiedReviewer": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803352/Portfolio%20Minh%20Huy/Ang%20Ang/UI/verified-reviewer.svg",
      "publicId": "Portfolio Minh Huy/Ang Ang/UI/verified-reviewer",
      "bytes": 428354,
      "width": 375,
      "height": 812,
      "format": "svg"
    }
  },
  "nepNha": {
    "thumbnail": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803355/Portfolio%20Minh%20Huy/Nep%20Nha/Brand/thumbnail.png",
      "publicId": "Portfolio Minh Huy/Nep Nha/Brand/thumbnail",
      "bytes": 133753,
      "width": 1490,
      "height": 1559,
      "format": "png"
    },
    "logoMark": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803356/Portfolio%20Minh%20Huy/Nep%20Nha/Brand/logo-mark.svg",
      "publicId": "Portfolio Minh Huy/Nep Nha/Brand/logo-mark",
      "bytes": 4388,
      "width": 66,
      "height": 59,
      "format": "svg"
    },
    "onboarding": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803358/Portfolio%20Minh%20Huy/Nep%20Nha/UI/onboarding.png",
      "publicId": "Portfolio Minh Huy/Nep Nha/UI/onboarding",
      "bytes": 234858,
      "width": 375,
      "height": 812,
      "format": "png"
    },
    "today": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803359/Portfolio%20Minh%20Huy/Nep%20Nha/UI/today.png",
      "publicId": "Portfolio Minh Huy/Nep Nha/UI/today",
      "bytes": 64805,
      "width": 375,
      "height": 812,
      "format": "png"
    },
    "family": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803360/Portfolio%20Minh%20Huy/Nep%20Nha/UI/family.png",
      "publicId": "Portfolio Minh Huy/Nep Nha/UI/family",
      "bytes": 117443,
      "width": 512,
      "height": 1698,
      "format": "png"
    },
    "home": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803362/Portfolio%20Minh%20Huy/Nep%20Nha/UI/home.png",
      "publicId": "Portfolio Minh Huy/Nep Nha/UI/home",
      "bytes": 343234,
      "width": 512,
      "height": 1894,
      "format": "png"
    },
    "memories": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803363/Portfolio%20Minh%20Huy/Nep%20Nha/UI/memories.png",
      "publicId": "Portfolio Minh Huy/Nep Nha/UI/memories",
      "bytes": 208676,
      "width": 512,
      "height": 1109,
      "format": "png"
    }
  },
  "meMe": {
    "home": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803364/Portfolio%20Minh%20Huy/MeMe/UI/home.jpg",
      "publicId": "Portfolio Minh Huy/MeMe/UI/home",
      "bytes": 2394154,
      "width": 1440,
      "height": 6584,
      "format": "jpg"
    },
    "gu": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803366/Portfolio%20Minh%20Huy/MeMe/UI/gu.jpg",
      "publicId": "Portfolio Minh Huy/MeMe/UI/gu",
      "bytes": 1499021,
      "width": 1440,
      "height": 5040,
      "format": "jpg"
    },
    "accessories": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803367/Portfolio%20Minh%20Huy/MeMe/UI/accessories.jpg",
      "publicId": "Portfolio Minh Huy/MeMe/UI/accessories",
      "bytes": 404796,
      "width": 1440,
      "height": 2374,
      "format": "jpg"
    },
    "shirts": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803368/Portfolio%20Minh%20Huy/MeMe/UI/shirts.jpg",
      "publicId": "Portfolio Minh Huy/MeMe/UI/shirts",
      "bytes": 387372,
      "width": 1440,
      "height": 2374,
      "format": "jpg"
    },
    "cart": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803369/Portfolio%20Minh%20Huy/MeMe/UI/cart.jpg",
      "publicId": "Portfolio Minh Huy/MeMe/UI/cart",
      "bytes": 145841,
      "width": 1440,
      "height": 1278,
      "format": "jpg"
    },
    "search": {
      "secureUrl": "https://res.cloudinary.com/dlasbipjr/image/upload/v1784803370/Portfolio%20Minh%20Huy/MeMe/UI/search.jpg",
      "publicId": "Portfolio Minh Huy/MeMe/UI/search",
      "bytes": 43503,
      "width": 1440,
      "height": 324,
      "format": "jpg"
    }
  }
} as const;
